-- Script that creates the MySQL server user user_0d_1
CREATE_USER_SQL="CREATE USER IF NOT EXISTS '$NEW_USER'@'localhost' IDENTIFIED BY '$NEW_USER_PASSWORD';"
GRANT_PRIVILEGES_SQL="GRANT ALL PRIVILEGES ON *.* TO '$NEW_USER'@'localhost' WITH GRANT OPTION;"
FLUSH_PRIVILEGES_SQL="FLUSH PRIVILEGES;"
